"""
Sentinel-AI Local System Adapter.

Real integration that performs tangible local actions (e.g. writing files,
generating reports) on the host machine to demonstrate physical automation.
"""

import os
import aiofiles
from datetime import datetime
from typing import Any

from sentinel_ai.integrations.base import BaseIntegration
from sentinel_ai.utils.logger import get_logger

logger = get_logger("integrations.local_system")

class LocalSystemAdapter(BaseIntegration):
    """
    Real Local File System integration.
    
    Supports:
    - Generating physical Markdown reports on the host OS.
    """

    def __init__(self):
        super().__init__(name="Local System", integration_type="file_system")
        self._reports_dir = os.path.join(os.getcwd(), "reports")

    async def connect(self) -> bool:
        """Connect to local system (ensure directories exist)."""
        try:
            os.makedirs(self._reports_dir, exist_ok=True)
            self._connected = True
            logger.info(f"Connected to local filesystem. Reports directory: {self._reports_dir}")
            return True
        except Exception as e:
            logger.error(f"Failed to connect to local filesystem: {e}")
            self._connected = False
            return False

    async def execute(self, action: str, data: dict) -> dict:
        """Execute a local action."""
        actions = {
            "write_report": self._write_report,
        }

        handler = actions.get(action)
        if not handler:
            return {"error": f"Unknown local action: {action}", "status": "failed"}

        try:
            return await handler(data)
        except Exception as e:
            logger.error(f"Local System action '{action}' failed: {e}")
            return {"error": str(e), "status": "failed"}

    async def _write_report(self, data: dict) -> dict:
        """Writes a physical markdown file summarizing the data."""
        timestamp = datetime.now().strftime("%Y-%m-%d_%H-%M-%S")
        workflow_type = data.get("workflow_type", "General")
        filename = f"{workflow_type}_Report_{timestamp}.md"
        filepath = os.path.join(self._reports_dir, filename)

        # Build a beautiful Markdown string out of the processed LLM JSON
        content = f"# 📊 {workflow_type.replace('_', ' ').title()} Official Report\n"
        content += f"*Generated by Sentinel-AI Execution Agent at {datetime.now().isoformat()}*\n\n"
        
        content += "## Input Context\n"
        content += f"> {data.get('content', 'No direct transcript provided.')}\n\n"
        
        content += "## Extracted Action Items & Decisions\n"
        for key, value in data.items():
            if key not in ["content", "workflow_type", "type", "workflow_id", "task_id"]:
                if isinstance(value, list):
                    content += f"### {key.title()}\n"
                    for item in value:
                        content += f"- {item}\n"
                    content += "\n"
                elif isinstance(value, dict):
                    content += f"### {key.title()}\n"
                    for k, v in value.items():
                        content += f"- **{k}**: {v}\n"
                    content += "\n"
                else:
                    content += f"- **{key.title()}**: {value}\n"

        # Asynchronously write to physical disk
        async with aiofiles.open(filepath, "w", encoding="utf-8") as file:
            await file.write(content)
            
        logger.info(f"✅ Successfully wrote physical report to: {filepath}")

        return {
            "status": "success", 
            "message": "File written physically to disk", 
            "filepath": filepath,
            "filename": filename
        }

    async def health_check(self) -> dict:
        return {
            "status": "healthy" if self._connected else "unhealthy",
            "connected": self._connected,
        }
